### ISSUE TITLE
Make cleanup before processing Addressables

### ISSUE THREAD

**Issue by PavelKlymentenkoSA** [StansAssets/com.stansassets.scene-management#34]
1. Clear Addressables cache - All. It might be at least a toggle.
![image](https://user-images.githubusercontent.com/66057791/185679633-2dad6474-6607-4db1-ab78-aa825126e1af.png)

3. Clear missing groups.
![image](https://user-images.githubusercontent.com/66057791/185679666-f0372771-7f24-4300-9557-e73525145f8d.png)

Sometimes it breaks a build process.

**Comment by alexey-yaremenko** [comment]
Done in #36
